server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:33060/authDB?createDatabaseIfNotExist=true
    username: root
    password: Ml22099478
    initialization-mode: always
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
  logging:
    level:
      org:
        hibernate:
          type: trace